FROM node:18
WORKDIR /app

# Copy only the package files and install dependencies
COPY backend/package*.json ./
RUN npm install

# Copy the rest of your backend source code
COPY backend/ .

EXPOSE 4001
CMD ["node", "src/server.js"]
