version: "3"
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    ports:
      - "4001:4001"
    environment:
      - PORT=4001
      - MONGODB_URI=mongodb+srv://dbUser:dbPassword@assign2.hfhxflx.mongodb.net/?retryWrites=true&w=majority&appName=assign2
      - JWT_SECRET=Zy2EXHMj7kkan7TNWasSfpGz2nfYkcuF
      - TOKEN_EXPIRES_IN=2h

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    ports:
      - "4200:80"
